//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEST_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMD_CONDITION_Rates
    {
        public int Id { get; set; }
        public string AltitudeUpdateRate { get; set; }
        public string ThrottleUpdateRate { get; set; }
        public string LatitudeUpdateRate { get; set; }
        public string RollUpdateRate { get; set; }
        public string PitchUpdateRate { get; set; }
        public string YawUpdateRate { get; set; }
    }
}
