//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEST_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMD_DO_Change_Speed : CMD_NAV_Takeoff
    {
        public Nullable<double> HorizontalSpeed { get; set; }
        public Nullable<double> VerticalSpeed { get; set; }
    }
}
