//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEST_App.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CommandsContainer : DbContext
    {
        public CommandsContainer()
            : base("name=CommandsContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CMD_NAV_Waypoint> CMD_NAV_Waypoint { get; set; }
        public virtual DbSet<CMD_NAV_Takeoff> CMD_NAV_Takeoff { get; set; }
        public virtual DbSet<CMD_CONDITION_Rates> CMD_CONDITION_Rates { get; set; }
        public virtual DbSet<CMD_NAV_Target> CMD_NAV_Target { get; set; }
        public virtual DbSet<CMD_NAV_Set_Base> CMD_NAV_Set_Base { get; set; }
        public virtual DbSet<CMD_NAV_Land> CMD_NAV_Land { get; set; }
    }
}
