//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEST_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public Equipment()
        {
            this.EuipmentHealth = new HashSet<EquipmentHealth>();
        }
    
        public int Id { get; set; }
        public int Type { get; set; }
        public string Name { get; set; }
        public string Vendor { get; set; }
        public string Manufacturer { get; set; }
        public decimal Price { get; set; }
        public double Weight { get; set; }
        public string Description { get; set; }
        public System.DateTime create_date { get; set; }
        public System.DateTime modified_date { get; set; }
    
        public virtual Configuration Configuration { get; set; }
        public virtual ICollection<EquipmentHealth> EuipmentHealth { get; set; }
    }
}
