//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEST_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentHealth
    {
        public int Id { get; set; }
        public double Health { get; set; }
        public string LastMaintenance { get; set; }
        public System.DateTime DateReceived { get; set; }
    
        public virtual Equipment EquipmentList { get; set; }
        public virtual UAV Vehicle { get; set; }
    }
}
