//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEST_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance
    {
        public System.DateTime last_maintenance { get; set; }
        public System.DateTime next_maintenance { get; set; }
        public string time_remaining { get; set; }
        public int id { get; set; }
        public int ScheduleId { get; set; }
        public System.DateTime create_date { get; set; }
        public System.DateTime modified_date { get; set; }
    
        public virtual Schedule Schedule { get; set; }
    }
}
