//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEST_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapInformation
    {
        public MapInformation()
        {
            this.Weather = new HashSet<Weather>();
        }
    
        public string ZoningInformation { get; set; }
        public string PopulationDensity { get; set; }
        public string Map_Latitude { get; set; }
        public string Map_Longitude { get; set; }
        public string ZoneName { get; set; }
        public string Map_Altitude { get; set; }
        public string SeaLevel { get; set; }
        public string SafeLandingLocation { get; set; }
        public string NonOwnShipAircraftPath { get; set; }
        public string MapInfoID { get; set; }
    
        public virtual ICollection<Weather> Weather { get; set; }
        public virtual UAVInformation UAVInformation { get; set; }
    }
}
