//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEST_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapRestricted
    {
        public int Id { get; set; }
        public double Corner1Latitude { get; set; }
        public double Corner1Longitude { get; set; }
        public double Corner2Latitude { get; set; }
        public double Corner2Longitude { get; set; }
        public double Ceiling { get; set; }
        public string Creator { get; set; }
        public System.DateTime TimeCreated { get; set; }
        public System.DateTime TimeEnds { get; set; }
        public string ReasonCreated { get; set; }
        public bool Warning { get; set; }
    }
}
