//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEST_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MissionLog
    {
        public MissionLog()
        {
            this.MissionLogActivities = new HashSet<MissionLogActivity>();
        }
    
        public int id { get; set; }
        public int Mission_id { get; set; }
        public System.DateTime create_date { get; set; }
        public System.DateTime modified_date { get; set; }
    
        public virtual Mission Mission { get; set; }
        public virtual ICollection<MissionLogActivity> MissionLogActivities { get; set; }
    }
}
