//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEST_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MissionLogActivity
    {
        public int id { get; set; }
        public int MissionLog_id { get; set; }
        public string action_taken { get; set; }
        public System.DateTime create_date { get; set; }
        public System.DateTime modified_date { get; set; }
        public string action_user_id { get; set; }
    
        public virtual MissionLog MissionLog { get; set; }
    }
}
