//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEST_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mission
    {
        public int Id { get; set; }
        public string Phase { get; set; }
        public string FlightPattern { get; set; }
        public string OffNominal { get; set; }
        public string Payload { get; set; }
        public string Priority { get; set; }
        public string Financials { get; set; }
        public string UAVAssigned { get; set; }
        public string TimeAssigned { get; set; }
        public string TimeCompleted { get; set; }
        public string Destination { get; set; }
        public string ScheduledCompletionTime { get; set; }
        public string EstimatedCompletionTime { get; set; }
    
        public virtual Orders Order { get; set; }
    }
}
