//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEST_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mission
    {
        public Mission()
        {
            this.Orders = new HashSet<Order>();
            this.MissionLogs = new HashSet<MissionLog>();
            this.Waypoints = new HashSet<Waypoint>();
        }
    
        public string Phase { get; set; }
        public string FlightPattern { get; set; }
        public string Payload { get; set; }
        public int Priority { get; set; }
        public Nullable<decimal> FinancialCost { get; set; }
        public System.DateTime TimeAssigned { get; set; }
        public System.DateTime TimeCompleted { get; set; }
        public System.Data.Entity.Spatial.DbGeography DestinationCoordinates { get; set; }
        public System.DateTime ScheduledCompletionTime { get; set; }
        public System.DateTime EstimatedCompletionTime { get; set; }
        public int id { get; set; }
        public int ScheduleId { get; set; }
        public System.DateTime create_date { get; set; }
        public System.DateTime modified_date { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual ICollection<MissionLog> MissionLogs { get; set; }
        public virtual ICollection<Waypoint> Waypoints { get; set; }
    }
}
