//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEST_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonownshipVehicle
    {
        public int Id { get; set; }
        public System.Data.Entity.Spatial.DbGeography Position { get; set; }
        public double Velocity { get; set; }
        public double VelocityX { get; set; }
        public double VelocityY { get; set; }
        public double VelocityZ { get; set; }
        public double Yaw { get; set; }
        public string FlightPlan { get; set; }
    }
}
