//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEST_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public System.DateTime TimeReceived { get; set; }
        public System.DateTime TimeCompleted { get; set; }
        public string PackageContents { get; set; }
        public string Notes { get; set; }
        public string DestinationAddress { get; set; }
        public int Mission_id { get; set; }
    
        public virtual Mission Mission { get; set; }
    }
}
