//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEST_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnshipVehicle
    {
        public OwnshipVehicle()
        {
            this.States = new HashSet<FlightState>();
            this.EuipmentHealths = new HashSet<EquipmentHealth>();
        }
    
        public int Id { get; set; }
        public string Callsign { get; set; }
        public int NumDeliveries { get; set; }
        public int Mileage { get; set; }
    
        public virtual ICollection<FlightState> States { get; set; }
        public virtual Configuration Configurations { get; set; }
        public virtual ICollection<EquipmentHealth> EuipmentHealths { get; set; }
    }
}
