//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEST_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestrictedArea : MapInformation
    {
        public RestrictedArea()
        {
            this.Weather1 = new HashSet<Weather>();
        }
    
        public string Restiricted_Latitude { get; set; }
        public string Restiricted_Longitude { get; set; }
        public string Restricited_Altitude { get; set; }
        public string Creator_Created { get; set; }
        public string Time_Created { get; set; }
        public string Reason_Created { get; set; }
        public string RestrictedAreaID { get; set; }
    
        public virtual ICollection<Weather> Weather1 { get; set; }
    }
}
