//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEST_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public Schedule()
        {
            this.Maintenances = new HashSet<Maintenance>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<Maintenance> Maintenances { get; set; }
        public virtual DeliveryStatus DeliveryStatus { get; set; }
    }
}
