//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEST_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAV_Warehouse : MapInfo
    {
        public UAV_Warehouse()
        {
            this.Weather1 = new HashSet<Weather>();
        }
    
        public string UACLocation { get; set; }
        public string ChargingStation { get; set; }
        public string MaintenanceCenter { get; set; }
        public string Warehouse { get; set; }
        public string CustomerControlRelevant_Facility { get; set; }
        public string UAV_WarehouseID { get; set; }
    
        public virtual ICollection<Weather> Weather1 { get; set; }
    }
}
