//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEST_App.Models
{
    using System;
    using NEST_App.Models;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NestContainer : DbContext
    {
        public NestContainer()
            : base("name=NestContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UAV> UAVs { get; set; }
        public virtual DbSet<FlightState> FlightStates { get; set; }
        public virtual DbSet<Configuration> Configurations { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<EquipmentHealth> EquipmentHealths { get; set; }
        public virtual DbSet<NonownshipVehicle> NonownshipVehicles { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Mission> Missions { get; set; }
        public virtual DbSet<Maintenance> Maintenances { get; set; }
        public virtual DbSet<MissionLog> MissionLogs { get; set; }
        public virtual DbSet<MissionLogActivity> MissionLogActivities { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<CMD_NAV_Waypoint> CMD_NAV_Waypoint { get; set; }
        public virtual DbSet<CMD_NAV_Takeoff> CMD_NAV_Takeoff { get; set; }
        public virtual DbSet<CMD_CONDITION_Rates> CMD_CONDITION_Rates { get; set; }
        public virtual DbSet<CMD_NAV_Target> CMD_NAV_Target { get; set; }
        public virtual DbSet<CMD_NAV_Set_Base> CMD_NAV_Set_Base { get; set; }
        public virtual DbSet<CMD_NAV_Land> CMD_NAV_Land { get; set; }
        public virtual DbSet<CMD_ACK> CMD_ACK { get; set; }
        public virtual DbSet<Waypoint> Waypoints { get; set; }
        public virtual DbSet<EventLog> EventLogs { get; set; }
        public virtual DbSet<MapArea> MapAreaSet { get; set; }
        public virtual DbSet<MapRestricted> MapRestrictedSet { get; set; }
        public virtual DbSet<MapPoint> MapPointSet { get; set; }
        public virtual DbSet<CMD_NAV_Return> CMD_NAV_Return { get; set; }
        public virtual DbSet<CMD_NAV_Hold> CMD_NAV_Hold { get; set; }
        public virtual DbSet<CMD_NAV_Adjust> CMD_NAV_Adjust { get; set; }
    }
}
