//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEST_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weather : MapRestricted
    {
        public string Location { get; set; }
        public string Name_Station { get; set; }
        public decimal AvgWindSpdMPH { get; set; }
        public decimal AvgWindDir { get; set; }
        public decimal MaxWindSpdMPH { get; set; }
        public decimal WindDiratMax { get; set; }
        public decimal AvgTempDeg_F { get; set; }
        public decimal MaxTempDeg_F { get; set; }
        public decimal MinTempDeg_F { get; set; }
        public decimal AvgRH_Perc { get; set; }
        public decimal AvgBarPress_mb { get; set; }
        public decimal TotalRainInches { get; set; }
        public decimal AvgSolar_WPerm2 { get; set; }
        public decimal BattVoltMin { get; set; }
    }
}
